__author__ = "isaerenc"

while True:
    istek = input("Kaç farklı dersinizin olduğunu seçiniz:\n 13\n 14\n 15\n 16\n 17\n 18\n :")
    if istek=="13":
        d1 = float(input("Lütfen dersin notunu giriniz:"))
        d2 = float(input("Lütfen dersin notunu giriniz:"))
        d3 = float(input("Lütfen dersin notunu giriniz:"))
        d4 = float(input("Lütfen dersin notunu giriniz:"))
        d5 = float(input("Lütfen dersin notunu giriniz:"))
        d6 = float(input("Lütfen dersin notunu giriniz:"))
        d7 = float(input("Lütfen dersin notunu giriniz:"))
        d8 = float(input("Lütfen dersin notunu giriniz:"))
        d9 = float(input("Lütfen dersin notunu giriniz:"))
        d10 = float(input("Lütfen dersin notunu giriniz:"))
        d11 = float(input("Lütfen dersin notunu giriniz:"))
        d12 = float(input("Lütfen dersin notunu giriniz:"))
        d13 = float(input("Lütfen dersin notunu giriniz:"))
        print("Yıl sonu ortalamanız:", (d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12+d13)/13)

    elif istek=="14":
        d1 = float(input("Lütfen dersin notunu giriniz:"))
        d2 = float(input("Lütfen dersin notunu giriniz:"))
        d3 = float(input("Lütfen dersin notunu giriniz:"))
        d4 = float(input("Lütfen dersin notunu giriniz:"))
        d5 = float(input("Lütfen dersin notunu giriniz:"))
        d6 = float(input("Lütfen dersin notunu giriniz:"))
        d7 = float(input("Lütfen dersin notunu giriniz:"))
        d8 = float(input("Lütfen dersin notunu giriniz:"))
        d9 = float(input("Lütfen dersin notunu giriniz:"))
        d10 = float(input("Lütfen dersin notunu giriniz:"))
        d11 = float(input("Lütfen dersin notunu giriniz:"))
        d12 = float(input("Lütfen dersin notunu giriniz:"))
        d13 = float(input("Lütfen dersin notunu giriniz:"))
        d14 = float(input("Lütfen dersin notunu giriniz:"))
        print("Yıl sonu ortalamanız:", (d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12+d13+d14) / 14)

    elif istek=="15":
        d1 = float(input("Lütfen dersin notunu giriniz:"))
        d2 = float(input("Lütfen dersin notunu giriniz:"))
        d3 = float(input("Lütfen dersin notunu giriniz:"))
        d4 = float(input("Lütfen dersin notunu giriniz:"))
        d5 = float(input("Lütfen dersin notunu giriniz:"))
        d6 = float(input("Lütfen dersin notunu giriniz:"))
        d7 = float(input("Lütfen dersin notunu giriniz:"))
        d8 = float(input("Lütfen dersin notunu giriniz:"))
        d9 = float(input("Lütfen dersin notunu giriniz:"))
        d10 = float(input("Lütfen dersin notunu giriniz:"))
        d11 = float(input("Lütfen dersin notunu giriniz:"))
        d12 = float(input("Lütfen dersin notunu giriniz:"))
        d13 = float(input("Lütfen dersin notunu giriniz:"))
        d14 = float(input("Lütfen dersin notunu giriniz:"))
        d15 = float(input("Lütfen dersin notunu giriniz:"))
        print("Yıl sonu ortalamanız:", (d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12+d13+d14+d15) / 15)

    elif istek=="16":
        d1 = float(input("Lütfen dersin notunu giriniz:"))
        d2 = float(input("Lütfen dersin notunu giriniz:"))
        d3 = float(input("Lütfen dersin notunu giriniz:"))
        d4 = float(input("Lütfen dersin notunu giriniz:"))
        d5 = float(input("Lütfen dersin notunu giriniz:"))
        d6 = float(input("Lütfen dersin notunu giriniz:"))
        d7 = float(input("Lütfen dersin notunu giriniz:"))
        d8 = float(input("Lütfen dersin notunu giriniz:"))
        d9 = float(input("Lütfen dersin notunu giriniz:"))
        d10 = float(input("Lütfen dersin notunu giriniz:"))
        d11 = float(input("Lütfen dersin notunu giriniz:"))
        d12 = float(input("Lütfen dersin notunu giriniz:"))
        d13 = float(input("Lütfen dersin notunu giriniz:"))
        d14 = float(input("Lütfen dersin notunu giriniz:"))
        d15 = float(input("Lütfen dersin notunu giriniz:"))
        d16 = float(input("Lütfen dersin notunu giriniz:"))
        print("Yıl sonu ortalamanız:", (d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12+d13+d14+d15+d16)/16)

    elif istek=="17":
        d1 = float(input("Lütfen dersin notunu giriniz:"))
        d2 = float(input("Lütfen dersin notunu giriniz:"))
        d3 = float(input("Lütfen dersin notunu giriniz:"))
        d4 = float(input("Lütfen dersin notunu giriniz:"))
        d5 = float(input("Lütfen dersin notunu giriniz:"))
        d6 = float(input("Lütfen dersin notunu giriniz:"))
        d7 = float(input("Lütfen dersin notunu giriniz:"))
        d8 = float(input("Lütfen dersin notunu giriniz:"))
        d9 = float(input("Lütfen dersin notunu giriniz:"))
        d10 = float(input("Lütfen dersin notunu giriniz:"))
        d11 = float(input("Lütfen dersin notunu giriniz:"))
        d12 = float(input("Lütfen dersin notunu giriniz:"))
        d13 = float(input("Lütfen dersin notunu giriniz:"))
        d14 = float(input("Lütfen dersin notunu giriniz:"))
        d15 = float(input("Lütfen dersin notunu giriniz:"))
        d16 = float(input("Lütfen dersin notunu giriniz:"))
        d17 = float(input("Lütfen dersin notunu giriniz:"))
        print("Yıl sonu ortalamanız:", (d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12+d13+d14+d15+d16+d17) / 17)

    elif istek=="18":
        d1 = float(input("Lütfen dersin notunu giriniz:"))
        d2 = float(input("Lütfen dersin notunu giriniz:"))
        d3 = float(input("Lütfen dersin notunu giriniz:"))
        d4 = float(input("Lütfen dersin notunu giriniz:"))
        d5 = float(input("Lütfen dersin notunu giriniz:"))
        d6 = float(input("Lütfen dersin notunu giriniz:"))
        d7 = float(input("Lütfen dersin notunu giriniz:"))
        d8 = float(input("Lütfen dersin notunu giriniz:"))
        d9 = float(input("Lütfen dersin notunu giriniz:"))
        d10 = float(input("Lütfen dersin notunu giriniz:"))
        d11 = float(input("Lütfen dersin notunu giriniz:"))
        d12 = float(input("Lütfen dersin notunu giriniz:"))
        d13 = float(input("Lütfen dersin notunu giriniz:"))
        d14 = float(input("Lütfen dersin notunu giriniz:"))
        d15 = float(input("Lütfen dersin notunu giriniz:"))
        d16 = float(input("Lütfen dersin notunu giriniz:"))
        d17 = float(input("Lütfen dersin notunu giriniz:"))
        d18 = float(input("Lütfen dersin notunu giriniz:"))
        print("Yıl sonu ortalamanız:", (d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12+d13+d14+d15+d16+d17+d18) / 18)

    else:
        print("Yanlış Giriş Yaptınız. Lütfen desteklediğimiz ders sayı gruplarından birini seçiniz (13'den 18'e kadar tüm ders saatlerini destekliyoruz').")
        #Bu uygulama size tam olarak yıl sonu ortalamanızı vermez. Bu uygulamada ders saatleri (ağırlıkları) hesaba katılmamaktadır. Bu yüzden sadece yakın bir sonuç alabilirsiniz.